/* automatically generated by rust-bindgen 0.71.1 */

pub const TS_ANY: i32 = -2;
pub const TS_START: i32 = -1;
pub const TS_END: i32 = 0;
pub const TS_SPACE: i32 = 1;
pub const TS_WORD: i32 = 2;
pub const TS_COMPOUND: i32 = 3;
pub const TS_PUNCTSTRONG: i32 = 4;
pub const TS_PUNCT: i32 = 5;
pub const TS_NUMBER: i32 = 6;
pub const TS_URL: i32 = 7;
pub const TS_CITEKEY: i32 = 8;
pub const TS_EMOTICON: i32 = 9;
pub const TS_EMOJI: i32 = 10;
pub const TS_ABBREV: i32 = 11;
pub const TS_CTRL: i32 = 12;
pub const TS_ORDINAL: i32 = 13;
pub const TS_NEWLINE: i32 = 14;
pub const TS_SPACESIGN: i32 = 15;
pub const TS_LASTNUM: i32 = 15;
pub type jchar = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TParser {
    str_: *mut jchar,
    strlen: ::std::os::raw::c_int,
    pos: ::std::os::raw::c_int,
    pub tlen: ::std::os::raw::c_int,
    pub tidx: ::std::os::raw::c_int,
    pub ttype: ::std::os::raw::c_int,
    _str: *mut ::std::os::raw::c_char,
    _mb: ::std::os::raw::c_int,
    _pos: ::std::os::raw::c_int,
    _len: ::std::os::raw::c_int,
    _next: ::std::os::raw::c_int,
    _prev: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of TParser"][::std::mem::size_of::<TParser>() - 64usize];
    ["Alignment of TParser"][::std::mem::align_of::<TParser>() - 8usize];
    ["Offset of field: TParser::str_"][::std::mem::offset_of!(TParser, str_) - 0usize];
    ["Offset of field: TParser::strlen"][::std::mem::offset_of!(TParser, strlen) - 8usize];
    ["Offset of field: TParser::pos"][::std::mem::offset_of!(TParser, pos) - 12usize];
    ["Offset of field: TParser::tlen"][::std::mem::offset_of!(TParser, tlen) - 16usize];
    ["Offset of field: TParser::tidx"][::std::mem::offset_of!(TParser, tidx) - 20usize];
    ["Offset of field: TParser::ttype"][::std::mem::offset_of!(TParser, ttype) - 24usize];
    ["Offset of field: TParser::_str"][::std::mem::offset_of!(TParser, _str) - 32usize];
    ["Offset of field: TParser::_mb"][::std::mem::offset_of!(TParser, _mb) - 40usize];
    ["Offset of field: TParser::_pos"][::std::mem::offset_of!(TParser, _pos) - 44usize];
    ["Offset of field: TParser::_len"][::std::mem::offset_of!(TParser, _len) - 48usize];
    ["Offset of field: TParser::_next"][::std::mem::offset_of!(TParser, _next) - 52usize];
    ["Offset of field: TParser::_prev"][::std::mem::offset_of!(TParser, _prev) - 56usize];
};
unsafe extern "C" {
    pub fn get_token(pst: *mut TParser) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn init_parser(pst: *mut TParser, str_: *mut jchar, len: ::std::os::raw::c_int);
}
unsafe extern "C" {
    pub fn new_parser() -> TParser;
}
